import { useState } from "react"
import { useQuery } from "@tanstack/react-query"
import * as reportService from "@/services/report.service"
import type { WeeklyReport } from "@/services/report.service"
import { useAuth } from "@/context/AuthContext"
import { useActiveBusiness } from "@/hooks/useActiveBusiness"
import { formatDate, formatMoney } from "@/lib/format"
import { downloadCsv } from "@/lib/csv"
import { downloadPdfReport } from "@/lib/pdf"
import { EmptyState } from "@/components/EmptyState"
import { ErrorState } from "@/components/ErrorState"
import { SummaryStat } from "@/components/reports/SummaryStat"
import { DownloadMenu } from "@/components/reports/DownloadMenu"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { CalendarRange } from "lucide-react"
import { useTranslation } from "react-i18next"

// Today's date as YYYY-MM-DD, used as the default value for the date picker (any day
// within the desired week can be picked; the backend resolves the containing week).
function todayIso() {
  return new Date().toISOString().slice(0, 10)
}

// Builds CSV rows for the "Items sold" export: per-product quantity/revenue plus a total row.
function itemsSoldCsvRows(report: WeeklyReport, currency: string) {
  return [
    ["Items sold", `${report.weekStart} to ${report.weekEnd}`],
    ["Currency", currency],
    [],
    ["Product", "Quantity", "Revenue", "Profit"],
    ...report.byProduct.map((row) => [row.product.name, `${row.totalQuantity} ${row.product.unit}`, row.totalRevenue, row.totalProfit]),
    [],
    ["Total", "", report.summary.totalAmount, report.summary.totalProfit],
  ]
}

// Builds CSV rows for the "Full report" export: summary totals, a daily breakdown,
// and breakdowns by employee and by product.
function fullReportCsvRows(report: WeeklyReport, currency: string) {
  return [
    ["Weekly report", `${report.weekStart} to ${report.weekEnd}`],
    ["Currency", currency],
    [],
    ["Total sales", report.summary.totalAmount],
    ["Transactions", report.summary.totalTransactions],
    ["Avg / day", report.summary.avgDailySales ?? 0],
    ["Best day", report.summary.bestDay?.dayName ?? ""],
    ["Profit", report.summary.hasIncompleteCostData ? `${report.summary.totalProfit} (incomplete cost data)` : report.summary.totalProfit],
    [],
    ["Daily breakdown"],
    ["Date", "Day", "Total", "Transactions", "Profit"],
    ...report.dailyBreakdown.map((d) => [d.date, d.dayName, d.totalAmount, d.transactionCount, d.totalProfit]),
    [],
    ["By employee"],
    ["Employee", "Total", "Transactions", "Profit"],
    ...report.byEmployee.map((row) => [row.employee.fullName, row.totalAmount, row.transactionCount, row.totalProfit]),
    [],
    ["By product"],
    ["Product", "Quantity", "Revenue", "Profit"],
    ...report.byProduct.map((row) => [row.product.name, `${row.totalQuantity} ${row.product.unit}`, row.totalRevenue, row.totalProfit]),
  ]
}

/**
 * Reports tab showing sales for the calendar week containing the selected date:
 * total sales, transaction count, average per day, best day, a per-day bar chart
 * (built from simple `<li>` bars sized by relative amount), and breakdowns by
 * employee and by product. Includes "Items sold" and "Full report" exports (CSV/PDF).
 */
export function WeeklyReportTab() {
  const { t } = useTranslation()
  const { activeBusinessId } = useAuth()
  const activeBusiness = useActiveBusiness()
  const currency = activeBusiness?.currency ?? "USD"
  const [date, setDate] = useState(todayIso)

  const query = useQuery({
    queryKey: ["report-weekly", activeBusinessId, date],
    queryFn: () => reportService.getWeeklyReport(activeBusinessId!, date),
    enabled: !!activeBusinessId,
  })

  // Shared header fields for every PDF export below.
  const pdfHeader = () => ({
    businessName: activeBusiness?.name ?? "",
    businessLocation: activeBusiness?.location,
    title: "WEEKLY REPORT",
    dateLine: `${formatDate(query.data!.weekStart)} – ${formatDate(query.data!.weekEnd)}`,
  })

  const downloadItemsCsv = () => {
    if (!query.data) return
    downloadCsv(`weekly-items-sold-${query.data.weekStart}-to-${query.data.weekEnd}.csv`, itemsSoldCsvRows(query.data, currency))
  }
  const downloadItemsPdf = () => {
    if (!query.data) return
    const report = query.data
    downloadPdfReport(`weekly-items-sold-${report.weekStart}-to-${report.weekEnd}.pdf`, {
      ...pdfHeader(),
      sections: [
        {
          head: ["Product", "Quantity", "Revenue", "Profit"],
          body: report.byProduct.map((row) => [row.product.name, `${row.totalQuantity} ${row.product.unit}`, formatMoney(row.totalRevenue, currency), formatMoney(row.totalProfit, currency)]),
          foot: ["Total", "", formatMoney(report.summary.totalAmount, currency), formatMoney(report.summary.totalProfit, currency)],
        },
      ],
      footerNote: "Generated by VAE Inventory",
    })
  }
  const downloadFullCsv = () => {
    if (!query.data) return
    downloadCsv(`weekly-report-${query.data.weekStart}-to-${query.data.weekEnd}.csv`, fullReportCsvRows(query.data, currency))
  }
  const downloadFullPdf = () => {
    if (!query.data) return
    const report = query.data
    downloadPdfReport(`weekly-report-${report.weekStart}-to-${report.weekEnd}.pdf`, {
      ...pdfHeader(),
      sections: [
        {
          heading: "Summary",
          head: ["Metric", "Value"],
          body: [
            ["Total sales", formatMoney(report.summary.totalAmount, currency)],
            ["Transactions", report.summary.totalTransactions],
            ["Avg / day", formatMoney(report.summary.avgDailySales ?? 0, currency)],
            ["Best day", report.summary.bestDay?.dayName ?? ""],
            ["Profit", formatMoney(report.summary.totalProfit, currency) + (report.summary.hasIncompleteCostData ? " *" : "")],
          ],
        },
        {
          heading: "Daily breakdown",
          head: ["Date", "Day", "Total", "Transactions", "Profit"],
          body: report.dailyBreakdown.map((d) => [d.date, d.dayName, formatMoney(d.totalAmount, currency), d.transactionCount, formatMoney(d.totalProfit, currency)]),
        },
        {
          heading: "By employee",
          head: ["Employee", "Total", "Transactions", "Profit"],
          body: report.byEmployee.map((row) => [row.employee.fullName, formatMoney(row.totalAmount, currency), row.transactionCount, formatMoney(row.totalProfit, currency)]),
        },
        {
          heading: "By product",
          head: ["Product", "Quantity", "Revenue", "Profit"],
          body: report.byProduct.map((row) => [row.product.name, `${row.totalQuantity} ${row.product.unit}`, formatMoney(row.totalRevenue, currency), formatMoney(row.totalProfit, currency)]),
          foot: ["Total", "", formatMoney(report.summary.totalAmount, currency), formatMoney(report.summary.totalProfit, currency)],
        },
      ],
      footerNote: "Generated by VAE Inventory",
    })
  }

  const dateControls = (
    <div className="flex flex-wrap items-center gap-2">
      <Input type="date" value={date} onChange={(e) => setDate(e.target.value)} className="w-auto" />
      <span className="text-xs text-muted-foreground">{t("Pick any day in the week")}</span>
      <DownloadMenu
        className="ml-auto"
        disabled={!query.data}
        groups={[
          { label: "Items sold", items: [{ label: "CSV", onClick: downloadItemsCsv }, { label: "PDF", onClick: downloadItemsPdf }] },
          { label: "Full report", items: [{ label: "CSV", onClick: downloadFullCsv }, { label: "PDF", onClick: downloadFullPdf }] },
        ]}
      />
    </div>
  )

  if (query.isLoading) {
    return (
      <div className="space-y-4">
        {dateControls}
        <Skeleton className="h-64 rounded-xl" />
      </div>
    )
  }
  if (query.isError) {
    return (
      <div className="space-y-4">
        {dateControls}
        <ErrorState onRetry={() => query.refetch()} />
      </div>
    )
  }
  const report = query.data
  if (!report) return null

  if (report.summary.totalTransactions === 0) {
    return (
      <div className="space-y-4">
        {dateControls}
        <EmptyState
          icon={<CalendarRange className="size-6" />}
          title="No sales this week"
          description={`${formatDate(report.weekStart)} – ${formatDate(report.weekEnd)}`}
        />
      </div>
    )
  }

  // Denominator for the daily-breakdown bar widths; floored at 1 to avoid divide-by-zero
  // when every day in the week had zero sales.
  const maxDayAmount = Math.max(...report.dailyBreakdown.map((d) => d.totalAmount), 1)

  return (
    <div className="space-y-4">
      {dateControls}
      <div className="grid grid-cols-2 gap-4 md:grid-cols-5">
        <SummaryStat label="Total sales" value={formatMoney(report.summary.totalAmount, currency)} />
        <SummaryStat label="Transactions" value={report.summary.totalTransactions} />
        <SummaryStat
          label="Avg / day"
          value={formatMoney(report.summary.avgDailySales ?? 0, currency)}
        />
        <SummaryStat
          label="Best day"
          value={report.summary.bestDay ? report.summary.bestDay.dayName : "—"}
        />
        <SummaryStat label="Profit" value={formatMoney(report.summary.totalProfit, currency)} />
      </div>
      {report.summary.hasIncompleteCostData && (
        <p className="text-xs text-muted-foreground">
          {t("Profit is based on products with a recorded cost price — some sales this week involved products with no cost price set, so this figure is incomplete.")}
        </p>
      )}

      <div className="rounded-xl border border-border p-4">
        <h3 className="mb-3 text-sm font-semibold">{t("Daily breakdown")}</h3>
        <ul className="space-y-2">
          {report.dailyBreakdown.map((day) => (
            <li key={day.date} className="flex items-center gap-3 text-sm">
              <span className="w-24 shrink-0 text-muted-foreground">{day.dayName}</span>
              <div className="h-2 flex-1 overflow-hidden rounded-full bg-muted">
                <div
                  className="h-full rounded-full bg-gradient-to-r from-primary to-success"
                  style={{ width: `${(day.totalAmount / maxDayAmount) * 100}%` }}
                />
              </div>
              <span className="w-28 shrink-0 text-right font-medium">
                {formatMoney(day.totalAmount, currency)}
              </span>
            </li>
          ))}
        </ul>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <div className="rounded-xl border border-border p-4">
          <h3 className="mb-3 text-sm font-semibold">{t("By employee")}</h3>
          <ul className="space-y-2 text-sm">
            {report.byEmployee.map((row) => (
              <li key={row.employee.id} className="flex justify-between">
                <span>{row.employee.fullName}</span>
                <span className="font-medium">{formatMoney(row.totalAmount, currency)}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="rounded-xl border border-border p-4">
          <h3 className="mb-3 text-sm font-semibold">{t("By product")}</h3>
          <ul className="space-y-2 text-sm">
            {report.byProduct.map((row) => (
              <li key={row.product.id} className="flex justify-between">
                <span>
                  {row.product.name} × {row.totalQuantity} {row.product.unit}
                </span>
                <span className="text-right">
                  <span className="block font-medium">{formatMoney(row.totalRevenue, currency)}</span>
                  <span className="block text-xs text-muted-foreground">
                    {t("Profit")}: {formatMoney(row.totalProfit, currency)}
                  </span>
                </span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  )
}
